### PR TITLE
Changes to statuses

### PR DESCRIPTION
**Pull request by thisisdano**
**Last updates before sprint review from me, I think**

- Added new status to PL documentation
- Updated colors to match design system
- Changed status badge dot

- - -

screen shot 2016-12-28 at 10 15 37 am

### CODE REVIEW

**Review by adborden — COMMENTED** [review]
I think most of us prefer the term "draft" over "wip". Why the need for beta? I feel like docs are kind of always incomplete, so draft signifies it hasn't been reviewed, but ready means it has.

**Comment by thisisdano** [comment]
OK — my opinions aren't strong on this.

**Comment by thisisdano** [comment]
@adborden OK — fixed.

**Review by line47 — APPROVED** [review]
This looks good to me!

**Pull request merged**
