### PR TITLE
Simple breadcrumbs

### PR DESCRIPTION
**Pull request by adborden**
This should be merged after
- [ ] https://github.com/18F/cg-style/pull/260 page header

screenshot from 2017-01-02 16-44-27

### CODE REVIEW

**Comment by adborden** [comment]
There's a few things that stick out to me,
- Is there a class to use to take care of the margins? It seems strange that panels handle the left/right padding. I'm using the grid here, but it doesn't account for the gutters. I would use panel, but it adds the white background. I feel like I had addressed something long ago between `.content` and `.grid` to handle this, but I can't remember what that is.
- I couldn't decide on the link color for the bread crumbs. we're using blue for links (and several other things), but also black/bold/underline in some cases. The black/bold/underline seems too strong for the breadcrumb, which shouldn't really draw your eye from the main content.

**Comment by adborden** [comment]
cc @thisisdano

**Comment by line47** [comment]
I agree with you @adborden we don't want the breadcrumbs too strong. I like them as blue links and feel that reinforces that they are clickable and not just informational. Underlining those breadcrumb links could also strengthen that they are in fact clickable.

**Review by line47 — COMMENTED** [review]
I think this looks good unless we have a class we can use to fit the content of the header that has already been established.

**Comment by thisisdano** [comment]
1. I love this
2. Blue links w/ underlines seems like the way to go
3. wrt margin/panel, etc I'm going to take a look at the margin/padding on the page header today, as well as the margin/padding in marketplace and in panel rows in general, so hopefully by EOD we'll have away forward for a consistent solution for margins/padding.
4. I think we should merge it asap and go from there.

**Review by thisisdano — APPROVED** [review]
maybe make underline change, but otherwise let's try to get this live asap and work from there.

**Pull request merged**
