### PR TITLE
Config for CircleCI 2.0

### PR DESCRIPTION
**Pull request by adborden**

### CODE REVIEW

**Review by siennathesane — COMMENTED** [review]
I think this is okay, I don't see a reason not to use CircleCI, could you provide some commentary on the reason?

**Comment by adborden** [comment]
cg-style was using the old 1.0 config format which has been sunset. This just brings it up to the 2.0 config version.

**Review by siennathesane — COMMENTED** [review]
I'm fine with this but I would like to see it in action.

**Review by siennathesane — APPROVED** [review]
LGTM

**Pull request merged**
