### PR TITLE
Creating a new pattern library for cg-style

### PR DESCRIPTION
**Pull request by juliasolorzano**
[Preview on Federalist](http://federalist.18f.gov.s3-website-us-east-1.amazonaws.com/site/18F/cg-style/)

This pull request is for the initial groundwork for a [Fractal](http://fractal.build/) based pattern library for the new styles for cloud.gov. It includes the 18f pages supported version of the previous style guide, [seen here](https://pages.18f.gov/cg-style/). This will be removed once the new style guide is launched.

NOTE: The `button` component and docs pages are meant as placeholders for now and are not meant to dictate the design decisions.

Refs https://github.com/18F/cg-style/issues/115

### CODE REVIEW

**Comment by msecret** [comment]
One thing that makes me a little nervous is having compiled files checked into the repo in the docs folder. Wasn't this something we had to undo in WDS because of the merge conflict problems? Or is that not a concern? Are there any other concerns around this?

I was also confused why there was a lot of similar files in `docs/build` and `docs/assets`. Whats the reason for that?

**Comment by juliasolorzano** [comment]
> One thing that makes me a little nervous is having compiled files checked into the repo in the docs folder. 

Because there is not a way to compile the files on Federalist now, we are needing to check-in the compiled files. However, @jeremiak has made me aware that he is working on a solve by adding the ability to run `npm run federalist` via build on Federalist. That said, just a reminder this is the initial work on the pattern library for us to build off of.

> I was also confused why there was a lot of similar files in docs/build and docs/assets. Whats the reason for that?

Yes. This is b/c running `npm run build-library` creates this build dir and compiles the files to run the site. Again, not optimal, but a place for us to start and build from! Open to other suggestions too.

**Comment by msecret** [comment]
OK that sounds good then. When FEderalist allows running npm we can move to not having the compiled files in.

**Comment by juliasolorzano** [comment]
@msecret right on - I will submit a separate pull request with that update once that solve is in Federalist!

**Comment by msecret** [comment]
Does @jeremiak need to see this? How should we merge?

**Comment by juliasolorzano** [comment]
@msecret since Jeremia and I paired on this work, my assumption was that he would not need to see it. Again, this is a starting ground for the initial work. IMHO it is totally up to you if it's okay to merge in.

**Pull request merged**
