### PR TITLE
Logo update

### PR DESCRIPTION
**Pull request by pburkholder**
Replaces #331 by updating logo in place (and styles weren't working for me, so just specified fill directly).

### CODE REVIEW

**Comment by siennathesane** [comment]
@mogul this one is pretty old, what do you want to do with it?

**Comment by siennathesane** [comment]
@brittag we should merge this or close it.

**Comment by pburkholder** [comment]
I'll close this. This was Phoebe's logo and I think it's never seen adoption since she left, and the current logo is fine.

**Comment by pburkholder** [comment]
https://github.com/18F/cg-style/blob/53b8f9ed4c9beef0faffb27658b6fac9a8abda60/src/img/logo.svg

To view the logo in question ^^^

**Pull request closed without merging**
